exports.ID = 'id';
// Users table
exports.USERS_TABLE = 'users';
exports.USERS_NAME = 'name';
exports.USERS_PASSWORD = 'password';
exports.USERS_ROLE = 'role';
exports.USERS_ROLE_ADMIN = 'admin';
// Games table
exports.GAMES_TABLE = 'games';
exports.GAMES_TITLE = 'title';